### ISSUE TITLE
link to weird / potentially dangerous site in your slide deck

### ISSUE THREAD

**Issue by balopat** [aaronclauset/aaronclauset.github.io#1]
Thank you for the interesting talk / slides on the role of prestige in scientific networks. I found an odd link that I think you should remove from the PDF though:

https://aaronclauset.github.io/slides/Clauset_2021_NetworksPrestigeAndTheSpreadOfScientificIdeas_SFI-CI.pdf
Slide 16: 

```
explore the data yourself:
http://danlarremore.com/faculty/
```

Probably the site was okay at one point but it went defunct since then and is sending people to obvious malware sites.

**Comment by aaronclauset** [comment]
Ah! Thanks for catching that. I've replaced the slide deck with a version with the correct link.
